### ISSUE TITLE
Mobile support? Is it inactive? Recommendations?

### ISSUE THREAD

**Issue by 01HD** [Paoda/melodii#1]
Is this program going to have mobile support? also, is this project inactive? It seems to have been a while since the last update and I think this is going to be a good project.

And last but not least, if this project is indeed not abandoned, I would like to recommend a feature: Smart playlist. Something simple really. Just music suggestions and stuff. Maybe some basic machine learning based on the genre of music?

**Comment by Paoda** [comment]
Mobile support is along the way


I will consider machine learning.
